# Generated by Django 2.2.12 on 2022-09-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0002_auto_20220919_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
