# Generated by Django 2.2.12 on 2022-10-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0005_basketitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitems',
            name='price',
        ),
    ]
