# Generated by Django 2.2.12 on 2022-10-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0006_remove_basketitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitems',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
