# Generated by Django 2.2.12 on 2022-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0007_basketitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
