# Generated by Django 2.2.12 on 2022-10-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0008_auto_20221004_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitems',
            name='price',
        ),
    ]
