# Generated by Django 2.2.12 on 2022-10-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0009_remove_basketitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
