# Generated by Django 2.2.12 on 2022-10-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0010_basketitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitems',
            name='imageurl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
